<definitions
  name=""
  targetNamespace="http://localhost:3000/users.wsdl"
  xmlns:tns="http://localhost:3000/users.wsdl"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsd1="./users.xsd"
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns="http://schemas.xmlsoap.org/wsdl/">
  <!-- definition of datatypes -->
  <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
          <import namespace ='xsd1' schemaLocation="users.xsd" />
      </schema>
  </types>

  <!-- response messages -->
  <message name='returns_id'>
    <part name='user' type='xsd:user'/>
  </message>

  <!-- request messages -->
  <message name='register'>
    <part name='id' type='xsd:id'/>
  </message>
  <message name='login'>
    <part name='id' type='xsd:id'/>
  </message>

  <!-- server's services -->
  <portType name='users'>
    <operation name='register'>
      <input message='tns:register'/>
      <output message='tns:returns_id'/>
    </operation>
    <operation name='login'>
      <input message='tns:login'/>
      <output message='tns:returns_id'/>
    </operation>
  </portType>

  <!-- server encoding -->
  <binding name='users_webservices' type='tns:users'>
    <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/>
    <operation name='register'>
      <soap:operation soapAction='urn:xmethods-delayed-quotes#register'/>
      <input>
        <soap:body use='encoded' namespace='urn:xmethods-delayed-quotes' encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/>
      </input>
      <output>
        <soap:body use='encoded' namespace='urn:xmethods-delayed-quotes' encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/>
      </output>
    </operation>
    <operation name='login'>
      <soap:operation soapAction='urn:xmethods-delayed-quotes#login'/>
      <input>
        <soap:body use='encoded' namespace='urn:xmethods-delayed-quotes' encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/>
      </input>
      <output>
        <soap:body use='encoded' namespace='urn:xmethods-delayed-quotes' encodingStyle='http://schemas.xmlsoap.org/soap/encoding/'/>
      </output>
    </operation>
  </binding>
  <!-- access to service provider -->
  <service name='users'>
    <port name='users_0' binding='users_webservices'>
      <soap:address location='http://127.0.0.1:3000/users'/>
    </port>
  </service>
</definitions>
